### ISSUE TITLE
Upgrade Dependencies for 0.2.0 Release

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#103]
Upgrade to newer versions of:
- de.hs-heilbronn.mi:crypto-utils
- de.hs-heilbronn.mi:db-test-utils
- de.hs-heilbronn.mi:jetty-utils
- de.hs-heilbronn.mi:log4j2-utils
- org.camunda.bpm:camunda-engine ...
- Jersey, Jetty, Spring, and others

**Comment by wetret** [comment]
Dependecies are updated for all except Camunda. @hhund Can you do the Camunda update?

I omitted upgrades of `tyrus` to version `2.0.0-M2` and `jersey` to version `3.0.0-M6` because they involve migrations to Jakarta EE.

**Comment by hhund** [comment]
Camunda upgrade 7.12 -> 7.13 done.
