### ISSUE TITLE
Make logs available on host 

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#11]
Currently logs are stored only in the container itself.

**Comment by SevKohler** [comment]
To add sufficient describtion to the issue:
Currently both java-application Servers are logging to sysout, this logs should be provided to the host via e.g. a docker volume

**Comment by wetret** [comment]
Also important would be ATNA logging in a central repository (e.g. logstash), and the logs from the reverse-proxies and the databases. 
Database logs are currently available in a mounted docker volume. The question is, if this is feasible or if these logs should also be made available in a central repository?

**Comment by hhund** [comment]
created new issue #65 for ATNA logging
