### ISSUE TITLE
Compute Simple Feasibility 0.2.0: Non valid Task resource send by TTP if no MeDIC result received

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#117]
Process computeSimpleFeasibility/0.2.0 generates an invalid Task resource to send back to the requesting MeDIC if no results where received and the timeout fired.

See also #116

**Comment by wetret** [comment]
I can think of several solutions here: 
  1. Use a different Task Profile / Message with its own Message Receive Event in the leading MeDIC to send a specific error
  2. Use the existing Task Profile / Message and send an Error as Part of the Input
  3. Send a 0 result for each cohort

**Comment by hhund** [comment]
I think a specific (new) Task profile should be the most expressive option. This way the default and the error case could independently be validated by FHIR.
