### ISSUE TITLE
Rework .gitignore

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#127]
Currently multiple `.gitignore` are used, only specifying files that are part of the same directory or module.

We might want to try consolidating all `.gitignore` files into one top level file. This file could contain general rules `**/foo` that apply everywhere and specialized rules for single files in specific locations.

**Comment by wetret** [comment]
In folders where all data should be ignored (for example the test certificates), I would leave the Gitignore files because they are responsible for the folder being in Git even though the folder is empty. What do you think @hhund?

**Comment by hhund** [comment]
Ah, I forgot about them. `README.md` files with a comment on why we have an empty folder here, might be more expressive tho'.
