### ISSUE TITLE
URL Not Found (Download Ubuntu Server 18.04.3 ISO)

### ISSUE THREAD

**Issue by alhersh** [highmed/highmed-dsf#187]
Hello,

The following link for the Ubuntu Server 18.04.3 ISO download is not found:

https://ftp-stud.hs-esslingen.de/pub/Mirrors/releases.ubuntu.com/18.04.3/ubuntu-18.04.3-live-server-amd64.iso.

Do I have to download this iso image specifically or can I use Ubuntu Shell under windows?

Regards,

Taha

**Comment by hhund** [comment]
For the 3MeDIC TTP Test setup please use the latest version of Ubuntu 18.04, the current one should be https://ftp-stud.hs-esslingen.de/pub/Mirrors/releases.ubuntu.com/18.04.5/ubuntu-18.04.5-live-server-amd64.iso
[Ubuntu 20.04](https://ftp-stud.hs-esslingen.de/pub/Mirrors/releases.ubuntu.com/20.04.2/) should work as well, but I haven't tested it yet.

Feel free to create a pull request that fixes the links mentioned in [test_setup_macos.txt](https://github.com/highmed/highmed-dsf/blob/develop/dsf-docker-test-setup-3medic-ttp/test_setup_macos.txt) and [test_setup_windows.txt](https://github.com/highmed/highmed-dsf/blob/develop/dsf-docker-test-setup-3medic-ttp/test_setup_windows.txt)
