### ISSUE TITLE
Make it possible to only deploy certain processes

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#19]
Depending on if your organization is a MeDIC or a TTP, you do not want to deploy and make available all process definitions.

**Comment by hhund** [comment]
The actual deployment of bpmn processes happens in org.highmed.dsf.bpe.plugin.AbstractProcessEnginePlugin#delpoy this might be a good place to decided if a deployment should happen or not based on the configured MeDIC or TTP type.

**Comment by wetret** [comment]
Depends on #58
