### ISSUE TITLE
TaskAuthorizationRule Should Support Process URLs Other Than http://highmed.org...

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#196]
The current TaskAutoriationRule only supports process URLs starting with http://highmed.org...
https://github.com/highmed/highmed-dsf/blob/fe19d75c79e33918c805a13698326934d271ead4/dsf-fhir/dsf-fhir-server/src/main/java/org/highmed/dsf/fhir/authorization/TaskAuthorizationRule.java#L36

We should consider replacing the `highmed.org` part with a general domain regex like `(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])` ([Source](https://stackoverflow.com/questions/106179/regular-expression-to-match-dns-hostname-or-ip-address#106223))

**Comment by hhund** [comment]
Since the BPMN process Id field does not allow for URL values we might need to add a URL prefix to the ProcessPluginDefinition in order to separate similar named processed from different projects. This might also require changes to the `org.highmed.dsf.bpe.process.excluded` and `org.highmed.dsf.bpe.process.retired` config properties.

**Comment by alhersh** [comment]
@alhersh  and @nlangh would like to work on this issue.

**Comment by hhund** [comment]
@alhersh and @nlangh feel free to provide a patch. Be aware that this code might be removed while I implement #179
