### ISSUE TITLE
Update Maven Dependencies

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#200]
For the 0.5.0 release we should update all maven dependencies where needed and if possible

**Comment by nlangh** [comment]
@nlangh and @alhersh would like to tackle this

**Comment by alhersh** [comment]
Pull request has been made for this issue at: #207

**Comment by hhund** [comment]
Before releasing 0.5.0 we need to check if any other dependencies need upgrades.

**Comment by alhersh** [comment]
Maven dependencies have been updated to last version. Pull request #230
