### ISSUE TITLE
Refreshing the page does not refresh the resource information

### ISSUE THREAD

**Issue by FloSeidel** [highmed/highmed-dsf#206]
While using the webfrontend of the FHIR Server refreshing the page (F5 / CTRL+R) isn't sufficient to receive updates on resources. 
As a workaround a cache clear does the job (CTRL+SHIFT+R).

**Comment by hhund** [comment]
I noticed this behavior of the html front-end while receiving Task resources from remote organizations and refreshing the `.../fhir/Task` url. Steps to reproduce might be:
1. Open `.../fhir/Task`
2. Create new Task ressource
3. Refresh `.../fhir/Task`

**Comment by hhund** [comment]
@alhersh or @nlangh could you look into this issues?

**Comment by hhund** [comment]
The issue (reversed logic) might be at two places:

https://github.com/highmed/highmed-dsf/blob/fe19d75c79e33918c805a13698326934d271ead4/dsf-fhir/dsf-fhir-server/src/main/java/org/highmed/dsf/fhir/webservice/impl/AbstractResourceServiceImpl.java#L327

https://github.com/highmed/highmed-dsf/blob/fe19d75c79e33918c805a13698326934d271ead4/dsf-fhir/dsf-fhir-server/src/main/java/org/highmed/dsf/fhir/dao/command/ReadCommand.java#L135
