### ISSUE TITLE
Refactor validation of absolute and logical references

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#227]
Access to absolute and logical references is strictly checked at the moment. This implementation should be refactored. A starting point could be the [ReferenceResolverImpl](https://github.com/highmed/highmed-dsf/blob/main/dsf-fhir/dsf-fhir-server/src/main/java/org/highmed/dsf/fhir/service/ReferenceResolverImpl.java) class. 

Absolute references to non DSF servers (i.e. no Endpoint resource is known) should not be checked and all logical references should be allowed to fail. We should configure enforcement of logical references only on certain resources where we only accept a DSF profile. Endpoint, Organization and OrganizationAffiliation could be such resources. In our CapabilityStatement for the server, we currently specify `logical` for all resources, see the FHIR Specification for details about [reference policy handling](http://hl7.org/fhir/valueset-reference-handling-policy.html). Accordingly, we wouldn't really expect the server to complain if they don't make sense. For the resource where it is hard enforced, we could then also specify `enforced`.

As an alternative, we could come up with an extension that can be attached to references to indicate that the integrity should not be checked.

**Comment by wetret** [comment]
Enforcement of logical references could be defined with the following extension to NamingSystem.uniqueId

```xml
<uniqueId>
  <type value="uri"/>
  <value value="http://highmed.org/sid/name"/>
  <extension url="http://highmed.org/fhir/StructureDefinition/extension-check-logical-reference" >
    <valueBoolean value="true"/>
  </extension>
</uniqueId>
```

**Comment by hhund** [comment]
Our implementation currently only works with uniqueIds of Type URI. Other logical reference types (OID, UUID and Other) currently can't be configured to be enforced.

Long term we need a better implementation, that either is more restrictive when allowing the creation of NamingSystem resources (uniqueId.value distinct across all uniqueId entries in all NamingSystem resources) or can distinguish between URI, OID, UUID or Other logical reference values, to decide which unqiueId entry fits and if it forces its references to exist.
