### ISSUE TITLE
Docker Secrets Reader Should Ignore Whitespace Characters

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#254]
Effected Versions: 0.5.0...

Currently the docker secrets reader uses the complete content of the secret file to define a password. We should trim the read content and maybe add a warning message, that the file ends e.g. in `LF`.

**Comment by hhund** [comment]
In order to reuse the same docker secret file when defining the password of the PostgreSQL docker image database owner user and the user used to run the database migration, our reader should be compatible with:

https://github.com/docker-library/postgres/blob/b4b726dbf1885e8e1543526ad9d250fdb2689cbb/docker-entrypoint.sh#L9-L25

and:

https://github.com/postgres/postgres/blob/REL_13_STABLE/src/interfaces/libpq/fe-connect.c#L7013 ff

**Comment by wetret** [comment]
According to the prostgres documentation of [initdb](https://www.postgresql.org/docs/9.5/app-initdb.html), which is used during startup of the docker container [here](https://github.com/docker-library/postgres/blob/b4b726dbf1885e8e1543526ad9d250fdb2689cbb/docker-entrypoint.sh#L82), only the first line of the will be used as password.
