### ISSUE TITLE
Plug-in Mechanism to add non Standard (local) Processes

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#28]
Implement plug-in mechanism to add non standard (local) processes. This would allow for the implementation of processes that are only use locally. This could also allow for specialized local sub-processes.

Generally speaking process JARs could be added to the BPE class-path via a docker volume. Local process specific FHIR StructureDefinitions can be added to the FHIR endpoint, via the existing external Bundle.

**Comment by wetret** [comment]
see merge request #49

**Comment by hhund** [comment]
see merged #48
