### ISSUE TITLE
Upgrade BPE Server to use Camunda 7.11

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#3]
Camunda 7.11.0 has been released. https://blog.camunda.com/post/2019/05/camunda-bpm-7110-released/ Upgrade the dsf-bpe project to use camunda release 7.11.0

Make sure to add db migration scripts from 7.10.0 to 7.11.0

**Comment by DWay17** [comment]
see https://docs.camunda.org/manual/latest/update/minor/710-to-711/
