### ISSUE TITLE
Create search parameter for ResearchStudy.enrollment

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#36]
Analog to Organization.endpoint. Enables include rest queries.

**Comment by hhund** [comment]
Currently ResearchStudy does not define an enrollment search parameter. Consultation with FHIR comunity necessary.

**Comment by wetret** [comment]
https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Search.20parameter.20for.20ResearchStudy.2EEnrollment

**Comment by wetret** [comment]
Change request for the new SearchParameter in the HL7 FHIR [Jira](https://jira.hl7.org/browse/FHIR-25239?filter=-2)
