### ISSUE TITLE
Fix typos in package-, class-, method-naming

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#37]
- org.highmed.dsf.bpe.plugin.AbstractProcessEnginePlugin#delpoy
- org.highmed.dsf.bpe.werbservice

**Comment by DWay17** [comment]
[f66018f_patch.diff.gz](https://github.com/highmed/highmed-dsf/files/3657810/f66018f_patch.diff.gz)

**Comment by DWay17** [comment]
oh zu spät

**Comment by hhund** [comment]
Ah cool, so viele fixes...

**Comment by wetret** [comment]
Merged in master with pull request #47
