### ISSUE TITLE
Extend ValueSet expression-language

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#39]
Currently only values of 
- text/cql
- text/fhirpath 
- application/x-fhir-query

but we also need aql and possibly ihe queries?

**Comment by wetret** [comment]
@hhund thoughts on how to expand the hapi value set defined in Expression.ExpressionLanguage?

**Comment by hhund** [comment]
The ValueSet http://hl7.org/fhir/ValueSet/expression-language includes all codes from https://www.hl7.org/fhir/codesystem-expression-language.html

One solution would be to create a CodeSystem with additional mime-types and than create a ValueSet that includes all codes from the new CodeSystem and from https://www.hl7.org/fhir/codesystem-expression-language.html

Another solution would be to have the FHIR community add the missing entries to https://www.hl7.org/fhir/codesystem-expression-language.html

**Comment by wetret** [comment]
Solution 1 is probably more feasible for a short term solution, but solution 2 would be preferred.

**Comment by wetret** [comment]
See [CodeSystem](https://github.com/highmed/highmed-dsf/blob/simple-feasibility-process/dsf-fhir/dsf-fhir-server/src/main/resources/fhir/CodeSystem/query-type-0.1.0.xml) and [ValueSet](https://github.com/highmed/highmed-dsf/blob/simple-feasibility-process/dsf-fhir/dsf-fhir-server/src/main/resources/fhir/ValueSet/query-type-0.1.0.xml). Does not work yet because validation is not based on profiles.

**Comment by wetret** [comment]
Hapi uses an enum for expression-language validation and throws an exception if the defined expression-language is not part of the enum. Question: Can this issue be resolved by profile validation or is it a bug in the hapi library?

**Comment by wetret** [comment]
Should be possible to fix this issue after updating to HAPI version 4.0.2. See #59.
