### ISSUE TITLE
Acces to openEHR

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#40]
We need a client to access the openEHR repositories. I see two possible options:

- Implement a client as part of the DSF following the openEHR spec
- Use a plugin system and an openEHR client has to be provided as jar (and maybe have a default client as part of the DSF)

**Comment by SevKohler** [comment]
FYI:
Birgers team is currently building a openEHR client which capsulated REST calls in a Java API. It also will have different functionalities e.g. AQL. It's still WIP and will be made open source next week.
So an third alternative would be helping them to implement the client so far that we can use it.

**Comment by wetret** [comment]
An openEHR client following the openEHR rest api for executing aql queries via post requests is implemented in branch 'openehr-client'. But interesting would be the json deserializer for ResultSets from Birgers team. This functionality is currently limited to count aql queries.

**Comment by hhund** [comment]
see merged #48
