### ISSUE TITLE
`mvn install` fails to install successfully

### ISSUE THREAD

**Issue by Threated** [highmed/highmed-dsf#400]
After cloning the repo and running `mvn install` it crashes with:
`Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.0.0-M7:verify (default) on project dsf-bpe-server`
The crashlog says:
`org.postgresql.util.PSQLException: ERROR: DROP DATABASE cannot be executed within a pipeline`

Docker version 23.0.1, build a5ee5b1

Java version:
```
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Ubuntu-0ubuntu122.04, mixed mode)
```

[Full crashlog xml document](https://github.com/highmed/highmed-dsf/files/11088605/Crashlog.txt)

**Comment by hhund** [comment]
Hello, @Threated 

thank you for the report. With one of the last minor releases PostgreSQL made a modification to the behavior of pipelines. Commands like `CREATE DATABASE` and `DROP DATABASE` now need to be executed as individual commands. See for example: https://www.postgresql.org/message-id/841565.1677254194%40sss.pgh.pa.us

If you want to build the current version of the DSF, I just pushed a fix (a6d0525) to the branch: `issues/400_postgresql_pipelines`
