### ISSUE TITLE
Prefer groupadd/useradd before addgroup/adduser in documentation

### ISSUE THREAD

**Issue by haemka** [highmed/highmed-dsf#408]
The [deployment codumentation](https://github.com/highmed/highmed-dsf/wiki/NUM%E2%80%90CODEX-DSF-0.9.2-Deployment#dsf-fhir-server) uses `addgroup` and `adduser` commands which are just wrappers for `groupadd` and `useradd`. Generally `groupadd` and `useradd` should be preferred, since the wrappers aren't available on all distributions. The syntax is also the same.

**Comment by schwzr** [comment]
Hi, thank you for your suggestion. 

As we move to DSF 1.x we will modify the documentation there (https://github.com/datasharingframework/datasharingframework.github.io).
