### ISSUE TITLE
Persist FHIR database outside docker postgres container

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#6]
Deleting the postgres container deletes all data as well.

**Comment by hhund** [comment]
For development and testing this is a feature. In production a persistent volume should be used for the database container.

Adding a volume like
```
volumes:
  - ./postgres-data:/var/lib/postgresql/data
```
to db entry in the compose file should do the trick.

@wetret could you check if this works, I haven't had time to test this yet.

**Comment by hhund** [comment]
fixed via pull request #7 

See compose files:
* https://github.com/highmed/highmed-dsf/blob/master/dsf-docker-test-setup/fhir/docker-compose.prod.yml
* https://github.com/highmed/highmed-dsf/blob/master/dsf-docker-test-setup/bpe/docker-compose.prod.yml

and wiki:
* https://github.com/highmed/highmed-dsf/wiki/Deployment-of-the-FHIR-Endpoint-using-Docker#build-and-running
* https://github.com/highmed/highmed-dsf/wiki/Deployment-of-the-BPE-using-Docker#build-and-running
