### ISSUE TITLE
Adapt simple feasibility for new Requirements

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#68]

**Comment by hhund** [comment]
Pull request #69 has been merged, feel free to close this issue if resolved and delete branch [feasibility-improvement](/highmed/highmed-dsf/tree/feasibility-improvement)

**Comment by wetret** [comment]
New requirements:
- All organizations are part of the request
- Result is only shown if more than 3 MeDICs answer
- Use include query for group download during research study download

**Comment by hhund** [comment]
fixed via #81

**Comment by hhund** [comment]
not merged into [master](https://github.com/highmed/highmed-dsf/tree/master) yet
