### ISSUE TITLE
Minimize Layers Created by fhir and bpe Docker Builds

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#84]
Currently two almost identical layers are created by the docker builds for the fhir and bpe app images.
The difference being, that the second layer has correct owners, groups and access rights set.

A multi-stage docker build can be used to combine these layers.

**Comment by wetret** [comment]
Merged with pull request #85

**Comment by hhund** [comment]
Reopening this issues: Not released yet, not merged into master yet.
