### ISSUE TITLE
Investigate proxy environment variables in docker compose files

### ISSUE THREAD

**Issue by wetret** [highmed/highmed-dsf#9]
HTTPS_SERVER_NAME_PORT

https://github.com/highmed/highmed-dsf/blob/master/dsf-docker-test-setup/fhir/docker-compose.yml

https://github.com/highmed/highmed-dsf/blob/master/dsf-docker-test-setup/bpe/docker-compose.yml

**Comment by hhund** [comment]
fixed with b7a8307
