### ISSUE TITLE
Implement Custom FHIR Operation to Delete Resources Permanently

### ISSUE THREAD

**Issue by hhund** [highmed/highmed-dsf#98]
The Operation should be able to delete all resource versions permanently from the database. Unfortunately the FHIR REST api currenlty does not define a standardized operation for this purpose.

**Comment by wetret** [comment]
First, a delete has to be executed:
`DELETE https://base-url/resource/id`

After that use the expunge operation:
`POST https://base-url/resource/id/$expunge`

with the following body:
```
{
    "resourceType": "Parameters",
    "parameter": [
         {
              "name": "expungeDeletedResources",
              "valueBoolean": true
         },{
              "name": "expungePreviousVersions",
              "valueBoolean": true
         }
     ]
} 
```

This deletes the resource and all of its previous versions permanently.
